---
# Use container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.4"

cache: pip

install:
  - pip install coveralls

script:
  - coverage run --source=src setup.py test

after_success:
  - coveralls

